#!/usr/bin/env python3
"""Generate the built-in role x permission matrix in guides/roles-and-access.mdx.

The matrix is derived from the permission registry in the cluster repository
(enginekit/authz/registry.go), never written by hand. The script compiles that
file on its own with a tiny driver, asks it for Registry() and BuiltinRoles(),
and rewrites the block between the role-matrix markers in the page.

    python3 scripts/gen_role_matrix.py --cluster-repo ../cluster            # rewrite
    python3 scripts/gen_role_matrix.py --cluster-repo ../cluster --check    # fail on drift

--ref picks the cluster revision (default origin/main; run `git fetch` in the
cluster checkout first). Needs git and a Go toolchain. Not run in Docs CI,
because the cluster repository is private.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys
import tempfile

PAGE = pathlib.Path(__file__).resolve().parent.parent / "guides" / "roles-and-access.mdx"
SOURCE = "enginekit/authz/registry.go"
START = "{/* role-matrix:start"
END = "{/* role-matrix:end */}"
ROLES = ["owner", "admin", "operator", "member", "viewer"]

# Presentation grouping only: every permission the registry holds is printed,
# and a domain missing from this map lands in "Other" rather than vanishing.
AREAS = [
    ("Organisation, people and audit", ["organisation", "members", "billing", "tokens", "audit"]),
    ("Clusters and Kubernetes", ["clusters", "agents", "kubernetes", "kube_access"]),
    ("Stacks, configuration and secrets", ["stacks", "variables", "profiles", "helm", "git", "sops", "credentials"]),
    ("Applications and delivery", ["applications", "pipelines", "promotions", "environments", "executions", "runs", "automations"]),
    ("Alerts, security and backups", ["alerts", "security", "backups"]),
    ("AI", ["ai", "ai_actions"]),
]

DRIVER = """package main

import (
	"encoding/json"
	"os"
)

type Permission string

func main() {
	type permissionOut struct {
		Permission  string `json:"permission"`
		Description string `json:"description"`
		IsWrite     bool   `json:"is_write"`
		HumanOnly   bool   `json:"human_only"`
	}
	type roleOut struct {
		Slug        string   `json:"slug"`
		Name        string   `json:"name"`
		Description string   `json:"description"`
		Permissions []string `json:"permissions"`
	}
	out := struct {
		Permissions []permissionOut `json:"permissions"`
		Roles       []roleOut       `json:"roles"`
	}{}
	for _, entry := range Registry() {
		out.Permissions = append(out.Permissions, permissionOut{string(entry.Permission), entry.Description, entry.IsWrite, IsHumanOnlyPermission(entry.Permission)})
	}
	for _, role := range BuiltinRoles() {
		granted := []string{}
		for _, permission := range role.Permissions {
			granted = append(granted, string(permission))
		}
		out.Roles = append(out.Roles, roleOut{role.Slug, role.Name, role.Description, granted})
	}
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	_ = encoder.Encode(out)
}
"""


def run(command: list[str], cwd: pathlib.Path | str | None = None) -> str:
    return subprocess.run(command, cwd=cwd, check=True, capture_output=True, text=True).stdout


def load_registry(cluster_repo: pathlib.Path, ref: str) -> tuple[dict, str]:
    commit = run(["git", "-C", str(cluster_repo), "rev-parse", ref]).strip()
    source = run(["git", "-C", str(cluster_repo), "show", f"{commit}:{SOURCE}"])
    source = re.sub(r"^package authz$", "package main", source, count=1, flags=re.M)
    with tempfile.TemporaryDirectory() as workdir:
        work = pathlib.Path(workdir)
        (work / "go.mod").write_text("module rolematrix\n\ngo 1.21\n")
        (work / "registry.go").write_text(source)
        (work / "main.go").write_text(DRIVER)
        data = json.loads(run(["go", "run", "."], cwd=work))
    return data, commit


def render(data: dict, commit: str) -> str:
    roles = {role["slug"]: set(role["permissions"]) for role in data["roles"]}
    missing = [slug for slug in ROLES if slug not in roles]
    if missing or len(roles) != len(ROLES):
        raise SystemExit(f"built-in roles changed: {sorted(roles)} (expected {ROLES}); update ROLES")

    by_domain: dict[str, list[dict]] = {}
    for entry in data["permissions"]:
        by_domain.setdefault(entry["permission"].split(".", 1)[0], []).append(entry)

    areas = [(title, [d for d in domains if d in by_domain]) for title, domains in AREAS]
    known = {d for _, domains in AREAS for d in domains}
    other = [d for d in by_domain if d not in known]
    if other:
        areas.append(("Other", other))

    lines = [
        f"{START} generated by scripts/gen_role_matrix.py from ankraio/cluster {SOURCE} at commit {commit}. Do not edit by hand. */}}",
        "",
    ]
    for title, domains in areas:
        if not domains:
            continue
        lines += [f"### {title}", ""]
        lines.append("| Permission | What it allows | " + " | ".join(f"`{slug}`" for slug in ROLES) + " |")
        lines.append("|---|---|" + "|".join(":-:" for _ in ROLES) + "|")
        for domain in domains:
            for entry in by_domain[domain]:
                name = entry["permission"]
                meaning = entry["description"].replace("|", "\\|")
                if entry["human_only"]:
                    meaning += " (human-only)"
                cells = ["✓" if name in roles[slug] else "" for slug in ROLES]
                lines.append(f"| `{name}` | {meaning} | " + " | ".join(cells) + " |")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cluster-repo", required=True, type=pathlib.Path)
    parser.add_argument("--ref", default="origin/main")
    parser.add_argument("--check", action="store_true", help="fail if the page does not match the registry")
    args = parser.parse_args()

    data, commit = load_registry(args.cluster_repo, args.ref)
    generated = render(data, commit)

    page = PAGE.read_text()
    start = page.find(START)
    end = page.find(END)
    if start < 0 or end < 0:
        raise SystemExit(f"{PAGE}: role-matrix markers not found")
    current = page[start : end + len(END)]

    # The commit line changes on every cluster commit; compare the tables only.
    def body(block: str) -> str:
        return block.split("\n", 1)[1]

    if args.check:
        if body(current) != body(generated):
            print(f"{PAGE.name}: role matrix is out of date with {SOURCE} at {commit}; run without --check", file=sys.stderr)
            return 1
        print(f"{PAGE.name}: role matrix matches {SOURCE} at {commit}")
        return 0

    PAGE.write_text(page[:start] + generated + page[end + len(END) :])
    print(f"{PAGE.name}: wrote the role matrix from {SOURCE} at {commit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
